[Add] Added KakaoLoginView
wecode-bootcamp-korea/32-2nd-GGSD-backend pull request #4
Opened 2022-05-13 07:10 UTC by imsooyeon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 소셜 로그인 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 소셜 로그인 기능 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- context manager 형식으로 atomic 사용

<br />

## :: 기타 질문 및 특이 사항

2022-05-13 08:05 UTC, kyeongraekim requested changes

2022-05-13 08:05 UTC, kyeongraekim commented on gaegosuder/settings.py
> +# }
깃헙에 올려주실 때는 로깅 부분을 삭제해주세요~

2022-05-13 08:05 UTC, kyeongraekim commented on users/views.py
> +            user_account  = response.json()
이 부분은 하나로 합치면 보다 깔끔해질 것 같네요!~

2022-05-13 08:05 UTC, kyeongraekim commented on users/views.py
> +            if User.objects.filter(email = user_account['kakao_account']['email']):
user_account는 유지/보수/관리에 용이하게 변수로 따로 담아서 관리해주세요~

2022-05-13 08:05 UTC, kyeongraekim commented on users/views.py
> +                    image_type_id = 5
image type이 하드코딩 되어 있네요~ 배포용 코드로 올려주시는 깃헙상 코드에는 하드코딩을 지양해주셔야 합니다~

2022-05-13 08:05 UTC, kyeongraekim commented on users/views.py
> +                    image_url = user_account['kakao_account']['profile']['profile_image_url'],
혹시 이미지랑 user를 연결하는 외래키는 생성시 연결이 없어도 될까요?

2022-05-13 08:05 UTC, kyeongraekim commented on users/views.py
> +                                    'access_token' : access_token}, status = 200)
추후 확장성을 고려하여서 이부분도 더 앞단에서 변수에 담아서 보내주시죠~

2022-05-13 09:24 UTC, imsooyeon commented on gaegosuder/settings.py
> +# }
삭제했습니다~

2022-05-13 09:24 UTC, imsooyeon commented on users/views.py
> +            user_account  = response.json()
수정했습니다~!

2022-05-13 09:25 UTC, imsooyeon commented on users/views.py
> +            if User.objects.filter(email = user_account['kakao_account']['email']):
넵 수정했습니다!

2022-05-13 09:25 UTC, imsooyeon commented on users/views.py
> +                                    'access_token' : access_token}, status = 200)
수정했습니당~!

2022-05-13 09:58 UTC, kyeongraekim requested changes
리베이스가 아직 되어있지 않네요 수연님! 아래 내용 간단히 추가 수정해주신 후 리베이스 하신 후 푸시해주세요!~

2022-05-13 09:58 UTC, kyeongraekim commented on users/views.py
> +                    image_type_id = 5
아직 하드코딩 된 부분이 보이네요!  각각의 image type들을 별도의 enum class에 담아서 관리해보세요~

2022-05-13 09:58 UTC, kyeongraekim commented on users/views.py
> +                                    'access_token' : access_token}, status = 200)
해당 부분은 JsonResponse 앞단에 reulst = 라는 변수에 담아서 해당 변수를 보내어주세요!~ 나중에 리턴메세지가 아닌 변수 선에서 코드를 수정하고 바꾸는게 더 추후 확장성에 용이합니다!~

2022-05-16 01:26 UTC, kyeongraekim requested changes
아래 마이너한 수정사항 반영해주시고 유닛테스트 까지 같이 재푸시해주세요!~

2022-05-16 01:26 UTC, kyeongraekim commented on users/views.py
> +    USER_PROFILE = 5
Enum Class에 담아주실 떄는 추후 확장성 및 이용가능성을 위해서 1~5에 해당되는 모든 PK 값을 선언해주세요~

2022-05-16 09:30 UTC, imsooyeon commented on users/views.py
> +    USER_PROFILE = 5
수정했습니다.

2022-05-16 10:25 UTC, kyeongraekim approved these changes
LGTM!~

2022-05-16 10:25 UTC, merged